export const POSTS = [
    {
        id: 1,
        author: "Sarah Jenkins",
        username: "@sarah_j",
        avatar: "/assets/flags/english.jpeg",
        badge: "Sage",
        timeAgo: "2 hours ago",
        content: "Best tips for remembering vocabulary faster? I've been struggling with Section 2 vocabulary lately. Does anyone have specific spaced repetition methods or mnemonic tricks that worked well for you?",
        likes: 24,
        comments: 8,
        isLiked: false,
    },
    {
        id: 2,
        author: "Budi Santoso",
        username: "@budi_s",
        avatar: "/assets/flags/indonesia.jpeg",
        badge: "Top 3 Leaderboard",
        timeAgo: "5 hours ago",
        content: "Completed my 30-day streak today! 🎉 Consistency is key! Making time for just 15 minutes every morning before work really made a huge difference. Don't give up on your daily quests!",
        likes: 56,
        comments: 14,
        isLiked: true,
    },
    {
        id: 3,
        author: "Claire Dupont",
        username: "@claire_d",
        avatar: "/assets/flags/french.jpeg",
        badge: "Overachiever",
        timeAgo: "1 day ago",
        content: "Grammar Question: Difference between 'Tolong' and 'Silakan'? Can a native speaker clarify when it's appropriate to use 'Tolong' versus 'Silakan' when asking someone to do something politely?",
        likes: 12,
        comments: 6,
        isLiked: false,
    },
];